# ASSIGNMENT

In [1]:
import numpy as np

In [120]:
import numpy as np
x = np.zeros(20)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
import numpy as np
v = np.arange(7,38)
print(v)

[ 7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30
 31 32 33 34 35 36 37]


In [14]:
a = np.arange(1385)
a

array([   0,    1,    2, ..., 1382, 1383, 1384])

In [15]:
a = np.arange(30, dtype=float)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29.])

In [16]:
a= np.arange(12).reshape((4, 3))
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [25]:
import numpy as np
a.dtype

dtype('int32')

In [31]:
import numpy as np
a = np.linspace(4,3,11)
a

array([4. , 3.9, 3.8, 3.7, 3.6, 3.5, 3.4, 3.3, 3.2, 3.1, 3. ])

In [32]:
import numpy as np
a = np.indices((5,5))
a

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [33]:
import numpy as np
z=[10, 11, 12 ,13, 14, 15, 16, 17, 18 ,19, 20, 21, 22 ,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48]
y=np.array(z)
np.reshape

<function numpy.reshape(a, newshape, order='C')>

In [35]:
a = np.array([[0,3.0,5],[0,7,0],(0+1j,3.,8)]).transpose() 
a

array([[0.+0.j, 0.+0.j, 0.+1.j],
       [3.+0.j, 7.+0.j, 3.+0.j],
       [5.+0.j, 0.+0.j, 8.+0.j]])

In [36]:
a= np.zeros((4,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
a = np.ones((4,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:

x = np.array([2.5,6,3.5,45])
y = np.array([0,1,2,3])
z = np.digitize(x,y)
z

array([3, 4, 4, 4], dtype=int64)

In [42]:
import numpy as np
a=np.array([3,6,9])
np.repeat(a,4)

array([3, 3, 3, 3, 6, 6, 6, 6, 9, 9, 9, 9])

import numpy as np
a=np.array([3,6,9])
np.repeat(a,4)

In [50]:
import numpy as np
x= np.random.randint(8)
print(x)
y = np.random.randint(1,7)
print(y)
z = np.random.randint(2,size=8)
print(z)
a = np.random.randint(1,7,size=10)
print(a)

3
3
[0 0 1 1 0 0 0 1]
[1 4 2 5 2 3 3 6 3 2]


In [51]:
import numpy as np
a=np.array([1,6,3,0,8])
np.tile(a,3)

array([1, 6, 3, 0, 8, 1, 6, 3, 0, 8, 1, 6, 3, 0, 8])

In [58]:
import numpy as np
x = np.random.choice(["Head","Tail"],size=8)
print(x)

['Tail' 'Tail' 'Head' 'Head' 'Head' 'Head' 'Head' 'Head']


In [61]:
x = np.random.choice([0,41,62,33,24,65,16])
print(x)
y = np.random.choice([1,2,3,4,5,6],size=100)
print(y)

62
[3 2 2 2 6 1 6 3 5 2 6 1 1 3 2 6 5 4 6 6 5 4 5 6 5 6 3 2 5 2 3 3 1 4 6 6 2
 1 3 2 5 2 5 3 4 5 3 5 5 4 6 4 1 4 4 2 4 6 5 4 2 2 1 1 1 4 2 6 2 5 2 6 2 3
 2 4 6 4 5 6 1 2 2 2 4 4 1 6 1 6 3 3 3 6 1 4 6 1 6 5]


In [64]:

a = np.random.binomial(10,0.5)
print(a)
b = np.random.binomial(10,0.8)
print(b)
flips = np.random.binomial(10,0.5,size=int(1e6))
(flips==4).mean()


3
8


0.204626

In [63]:
import numpy as np
a = np.random.rand(3,15)
a

array([[0.34603594, 0.15682607, 0.07725752, 0.96531585, 0.71843498,
        0.30770821, 0.91574726, 0.25572473, 0.33822946, 0.96129273,
        0.42631435, 0.94701231, 0.56770186, 0.06895785, 0.71978703],
       [0.4566208 , 0.97589168, 0.5768307 , 0.57831637, 0.15093053,
        0.90926374, 0.11916883, 0.58112111, 0.29376854, 0.05454337,
        0.83611669, 0.84878094, 0.66917276, 0.39846923, 0.99681649],
       [0.38989896, 0.9434089 , 0.04735117, 0.4428212 , 0.75109855,
        0.71317135, 0.0727345 , 0.00478847, 0.86169393, 0.86581739,
        0.81209798, 0.29088831, 0.52807188, 0.79986605, 0.52520699]])

In [65]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Bajwa/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Bajwa/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Bajwa/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Bajwa/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Bajwa/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Bajwa/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Bajwa/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Bajwa/anaconda3\\Library\\include']
None


In [66]:
import numpy as np
a = np.random.ranf(20)
print(a)

[0.73571804 0.23242929 0.6398936  0.75837763 0.37455125 0.98015211
 0.01244112 0.79081934 0.42008905 0.91786454 0.75639878 0.27881233
 0.39189351 0.00856942 0.66024446 0.48511006 0.8558253  0.90341675
 0.98827636 0.96093248]


In [67]:
import numpy as np
a = np.random.bytes(20)
print(a)

b'\xbe\x1b\xb0@[K\xb1\x08>\xac\x0c\x03U\xd21\x03*aUs'


In [19]:
# np.random.shuffle
arr = np.arange(10)
np.random.shuffle(arr)
print(arr)

[2 8 5 3 6 4 7 1 0 9]


In [68]:
import numpy as np
a = np.array([40,41,42,43,44,45,46,47,48])
print(a)
np.ndim(a)

[40 41 42 43 44 45 46 47 48]


1

In [69]:
a = np.arange(16).reshape((4,4))
np.random.permutation(a)


array([[ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [70]:
a = np.random.beta(1,50)
a

0.03934777049468756

In [71]:
a = np.random.chisquare(1,5)
a

array([4.05345368, 0.32373621, 0.34618053, 1.85065745, 0.32863725])

In [23]:
s = np.random.dirichlet((10, 5, 3),20).transpose()
print(s)

[[0.44245796 0.45902668 0.66066624 0.76603507 0.39643583 0.59288352
  0.80779877 0.5664818  0.68607239 0.38798394 0.43618462 0.48534926
  0.65245685 0.61554655 0.46825875 0.60465518 0.56906627 0.51390125
  0.33600417 0.4529029 ]
 [0.30111295 0.23950608 0.23882341 0.16285485 0.44070091 0.29933425
  0.10559894 0.22468882 0.26608384 0.50149904 0.21775868 0.35867391
  0.15728565 0.32073723 0.33249575 0.32936806 0.3277095  0.35730813
  0.34836539 0.31907065]
 [0.25642909 0.30146724 0.10051035 0.07111008 0.16286327 0.10778223
  0.08660228 0.20882939 0.04784377 0.11051702 0.3460567  0.15597682
  0.19025749 0.06371621 0.1992455  0.06597676 0.10322422 0.12879062
  0.31563044 0.22802645]]


In [80]:
import numpy as np
l=[40,41,42,43,44,45,46,47,48]
x=np.array(l)
x>9

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [84]:
import numpy as np
a = np.random.exponential(2)
a

1.7110892442524483

In [83]:
import numpy as np
x=np.zeros((30,30))
x.shape

(30, 30)

In [92]:
import numpy as np
x = np.zeros(10)
x[5] = 10
print(x)

[ 0.  0.  0.  0.  0. 10.  0.  0.  0.  0.]


In [93]:
z = np.random.geometric(p=0.15, size=300)
print(z)   

[ 8  2 21 10  2  9  1  5  2  2 10  1 23  4  2  1  4  6  6  3  9 19  6  2
  8 17  3  2 18 10  7  5  1  4 10  2  3 16 11  4  1  1 12  5  1  3  4  2
 12  4  3  5 17  5  3 10  2  3 36  1  3 14 16 31  4  1 18  1 36  8  7  2
  9 24  7 15  7  3  8  8  6  2 28  5 10  2  2  2 24  6  6 23  8  7  9 12
  5  3  4  1  7  1  3 16  2  1  1  8  3  7 22  4 15  2 23 18  4  4  1 14
  8  3  3  5  3  3  7  6  6  1 11  5  3  6  6  9 14 13  1 11 13  3  7 19
 13  6  2  9  4 15  5  1 26  3  1 10  1  2  8 10  2  6 12 12 12  1  1  6
 12  7 10  3  7 14  4  1 15  4  5  3  2  1  4  5  4 11  8  4  4  2  5  1
 12  1  6  1 15 12  2  8 11  4  1  2 17  2  2  2  2  3  5 13  8  8  2  7
  1 12  1  6  6  8 10 15  7  7  4  3  9 13 14 23  3  1  1  8  8  7  8  3
  2  1  6  4  1  4  2  1 14 15  3  5  2 26  1  4  3 11  6  8  3  6  6 15
  3 22  3  5  5 11  1  4  1  4  1  3  2  5 18  3  6  3  3  2  2  1 16 12
  3  2 11  4 12  3  3 21  4 10  2  5]


In [95]:
import numpy as np
a=np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [96]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5]) 
arr = arr.astype('float64') 
print(arr) 
print(arr.dtype)

[1. 2. 3. 4. 5.]
float64


In [101]:
import numpy as np
a = np.array([[1., 2., 3.],
            [4., 5., 6.]])
b = np.array([[0., 7., 8.],
           [10., 11., 12.]])
a*b

array([[ 0., 14., 24.],
       [40., 55., 72.]])

In [103]:
#Extract all odd numbers
a = np.array([0,1,2,3,4,5,6,7,8,9,40,41,42,43,44,45,46,47,48])
a[a % 2 == 1]

array([ 1,  3,  5,  7,  9, 41, 43, 45, 47])

In [104]:
# Replace all odd numbers to -1 

a = np.array([0,1,2,3,4,5,6,7,8,9])
-a[a % 2 == 1]

array([-1, -3, -5, -7, -9])

In [110]:
import numpy as np
a=np.arange(20)
a[5] 
a[5:9] 
a[5:9] = 10
print(a)

[ 0  1  2  3  4 10 10 10 10  9 10 11 12 13 14 15 16 17 18 19]


In [111]:
#2d array with 1 on the border and 0 inside
import numpy as np
x = np.ones((5,5))
x[1:-1,1:-1] = 0
print(x)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [114]:
x=np.arange(0,15)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [115]:
#positions where elements of a and b match
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a, b))

[2 4]


In [117]:
names = np.array(['Badar', 'sitara', 'Awais', 'Zara', 'Zaria', 'Zoni', 'Laiba'])
data = np.random.randn(7, 4)
print(names)
print(data)
data[names == 'Zara'] 


['Badar' 'sitara' 'Awais' 'Zara' 'Zaria' 'Zoni' 'Laiba']
[[ 2.71523046 -0.09585618  0.08510393 -0.67024059]
 [ 0.10533305  0.52644232  0.77179675 -0.00972703]
 [ 1.54188988 -2.45198778  0.370518   -0.53825297]
 [-0.04922073  1.42812761  0.83381298 -1.30254756]
 [-0.37257471  2.19881275  0.58674959 -1.37729168]
 [ 0.43757012 -0.35227167 -0.84254388  0.55614464]
 [-1.0659779   0.84134017 -0.85583973  0.49629916]]


array([[-0.04922073,  1.42812761,  0.83381298, -1.30254756]])

In [119]:
import numpy as np
x = np.arange(0,16)
y = x.reshape((4,4))
print(y)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [128]:
import numpy as np
a = np.arange(0,16)
x = a.reshape((2,2,4))
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [126]:
import numpy as np
x = np.arange(0,16)
y= x.reshape((2,2,4))
x = y.swapaxes(1, 2)
print(x)

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


In [129]:
import numpy as np
a = np.arange(20)
print(a)
z = np.sqrt(a ** 2)
print(z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]


In [130]:

import numpy as np
c=np.random.rand(2,3,4)
np.cumsum(c)
c

array([[[0.12880253, 0.36674699, 0.10209853, 0.34129031],
        [0.95038127, 0.99769741, 0.90445065, 0.80226383],
        [0.61508152, 0.54047165, 0.21437434, 0.44302885]],

       [[0.90405996, 0.33584453, 0.88612582, 0.78039204],
        [0.87662759, 0.04540074, 0.52324527, 0.53769488],
        [0.79224642, 0.9128655 , 0.52625627, 0.41734562]]])

In [131]:
names = np.unique(['Badar', 'sitara', 'Awais', 'Zara', 'Zaria', 'Zoni', 'Laiba'])
names=np.unique
np.unique(names)

array([<function unique at 0x000000937A314C10>], dtype=object)